### ISSUE TITLE
Cache directory should not be created unconditionally in setup.py

### ISSUE THREAD

**Issue by sparr** [akazukin5151/koneko#29]
https://github.com/akazukin5151/koneko/blob/master/setup.py#L11-L16

These steps are executed regardless of what directive was given to the setup script. `python setup.py` and `pip install --dry-run ...` should not trigger these steps.

See https://moyix.blogspot.com/2022/09/someones-been-messing-with-my-subnormals.html and https://twitter.com/moyix/status/1566612152558944257

**Comment by akazukin5151** [comment]
Thanks for opening the issue. This should have been spotted in 72869a18. Apparently it wasn't running for some people so I opted for a ... rather forcible method. Sorry for the inconvenience, hope you enjoyed those anime catgirls!
